name: hihihi
description: "A Flutter-based chatbot Application."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_sound: ^9.2.13
  just_audio: ^0.9.36
  audio_waveforms: ^1.0.4
  speech_to_text: ^6.5.1
  wave: ^0.2.2
  shared_preferences: ^2.0.6

  flutter_tts: ^3.2.0
  audioplayers: ^5.2.1
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.2
  google_sign_in: ^6.2.1
  google_fonts: ^6.1.0
  http: ^1.1.2
  animated_text_kit: ^4.2.2
  image_picker: ^1.0.5
  flutter_secure_storage: ^9.0.0
  intl: ^0.19.0
  vnlunar: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - lib/assets/icons/
